### PR TITLE
Wip/git with no extensions

### PR DESCRIPTION
**Pull request by briot**

### CODE REVIEW

**Comment by setton** [comment]
Hi Manu @briot !

Good to see ya! 

No objections to the patch so far. When you say "WIP", does this mean there's more coming? 

Also please sign the paperwork (it's per-project, very sorry for the hassle!)

Nico

**Comment by briot** [comment]
> Good to see ya!

I did not even remember the name of the directory for the scripts, had to
search for them….

> No objections to the patch so far. When you say "WIP", does this mean there's more coming?

No, that’s just the name of the branch.

> Also please sign the paperwork (it's per-project, very sorry for the hassle!)

Won’t do.
That’s a two line patch, so please integrate as is, or waste the work.
If AdaCore cannot integrate a patch with just one line of change without requiring
papers, they should just give up on the idea of building communities.
GPS is of limited interest to us, I am the first one even trying to use it here.

**Comment by setton** [comment]
Ok closing!

**Comment by setton** [comment]
Trust me, I am the first one to lament about the needs for more paperwork, and I really hope this will change in the near future and we can make it more flexible for small contributions...

**Pull request closed without merging**
